let map=new Map()
console.log(map)
map.set('Mum','16.08.1973')
map.set('Dad','22.11.1972')
map.set('Grandpa','xx.xx.xxxx')
//map.delete('Grandpa')
console.log(map.has('Mum'))
console.log(map.get('Mum'))
map.set('kakumicishi','kakumicishi')
console.log(map)